// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8xr2Fg0WCAAm6WkIRA903ceUhiU62RgY',
    appId: '1:803396809187:web:386d2e15ecfaf1446870d6',
    messagingSenderId: '803396809187',
    projectId: 'herogamesuserapp',
    authDomain: 'herogamesuserapp.firebaseapp.com',
    storageBucket: 'herogamesuserapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhMzES2eL8_oSszL6n9M6jjNZi1pdBRLI',
    appId: '1:803396809187:android:629550e9c9f7d1266870d6',
    messagingSenderId: '803396809187',
    projectId: 'herogamesuserapp',
    storageBucket: 'herogamesuserapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP-lRmd8560RHQwF1m95ClV_SpkybCLyQ',
    appId: '1:803396809187:ios:05d7f87af2036da16870d6',
    messagingSenderId: '803396809187',
    projectId: 'herogamesuserapp',
    storageBucket: 'herogamesuserapp.appspot.com',
    iosBundleId: 'com.example.heroGamesCase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP-lRmd8560RHQwF1m95ClV_SpkybCLyQ',
    appId: '1:803396809187:ios:e74d13c6492627476870d6',
    messagingSenderId: '803396809187',
    projectId: 'herogamesuserapp',
    storageBucket: 'herogamesuserapp.appspot.com',
    iosBundleId: 'com.example.heroGamesCase.RunnerTests',
  );
}
